        !COMPILER-GENERATED INTERFACE MODULE: Mon Sep 26 14:42:23 2022
        ! This source file is for reference only and may not completely
        ! represent the generated interface used by the compiler.
        MODULE PERMEABILITYCONSTRUCTOR__genmod
          INTERFACE 
            SUBROUTINE PERMEABILITYCONSTRUCTOR(ELEMENTBIPHASIC,         &
     &ELEMENTLIST,GLOBALNODESLIST,PERMEABILITY,ANALYSISSETTINGS)
              USE MODANALYSIS
              USE MODNODES
              USE MODELEMENTBIPHASIC
              CLASS (CLASSELEMENTBIPHASIC) ,POINTER :: ELEMENTBIPHASIC
              TYPE (CLASSELEMENTSWRAPPER) ,POINTER :: ELEMENTLIST(:)
              TYPE (CLASSNODES) ,POINTER :: GLOBALNODESLIST(:)
              CLASS (CLASSPERMEABILITYMODELWRAPPER) ,POINTER ::         &
     &PERMEABILITY
              TYPE (CLASSANALYSIS) :: ANALYSISSETTINGS
            END SUBROUTINE PERMEABILITYCONSTRUCTOR
          END INTERFACE 
        END MODULE PERMEABILITYCONSTRUCTOR__genmod
